paper/paper.bib, paper/paper.md
Added:
- New simulation framework.
- ReadTheDocs link.
Changed:
- Replace educational resource section with a single line in "Statement of Need". As there are no longer pieces of code to complete for the autocorrelation and the Real FFT.
=> Update JOSS paper.

.github/workflows/python_no_pycsou.yml, .github/workflows/python_pycsou.yml, pull_request_template.md
And limit GitHub actions to only when there are file changes.
=> Add PR template.

.gitignore, CHANGELOG.rst, configs/simulate_dataset.yaml, configs/simulate_torch_custom_dataset.yaml, lensless/admm.py, lensless/apgd.py, lensless/gradient_descent.py, lensless/io.py, lensless/metric.py, lensless/recon.py, lensless/unrolled_admm.py, lensless/unrolled_fista.py, lensless/util.py, scripts/sim/dataset.py, scripts/sim/single_file.py, scripts/sim/torch_custom_dataset.py, scripts/sim/torch_dataset.py, test/test_algos.py
=> Fix simulation examples.

configs/demo.yaml, scripts/recon/demo.py
=> Add support for unrolled

CHANGELOG.rst, lensless/io.py
=> Add support for npy image

configs/telegram_demo.yaml, scripts/demo/telegram_bot.py
=> Demo fixes

CONTRIBUTING.rst
=> Alternate way of building the documentation

.github/workflows/python_pycsou.yml, CHANGELOG.rst, README.rst, lensless/utils/image.py, test/test_io.py
=> Add torch support for rgb2gray.

CHANGELOG.rst, configs/fine-tune_PSF.yaml, configs/unrolled_recon.yaml, docs/requirements.txt, docs/source/dataset.rst, docs/source/mask.rst, lensless/hardware/trainable_mask.py, lensless/recon/recon.py, lensless/recon/rfft_convolve.py, lensless/recon/trainable_mask.py, lensless/recon/utils.py, lensless/utils/dataset.py, lensless/utils/simulation.py, mask_requirements.txt, recon_requirements.txt, scripts/recon/train_unrolled.py
Add support for trainable mask.
=> Trainable mask

README.rst
=> Fix readme rendering.

README.rst
=> Add lensless image download badge

scripts/recon/train_unrolled.py, scripts/sim/digicam_psf.py
=> Small changes.

CHANGELOG.rst, setup.py
=> Fix submodule.

CHANGELOG.rst, lensless/hardware/trainable_mask.py
=> Fix AdafruitLCD input handling.

configs/upload_dataset_huggingface.yaml, configs/upload_digicam_mirflickr_multimask.yaml, scripts/data/upload_dataset_huggingface.py
=> Add support to upload multimask dataset to Hugging Face.

README.rst, rpi_requirements.txt
=> Update RPi setup.

configs/collect_dataset.yaml, configs/collect_mirflickr_multimask.yaml, configs/collect_mirflickr_singlemask.yaml, lensless/hardware/slm.py, scripts/measure/collect_dataset_on_device.py, scripts/measure/prep_display_image.py
=> Add support for multimask measurement.

configs/upload_dataset_huggingface.yaml, scripts/data/upload_dataset_huggingface.py
=> Improvements to dataset upload

README.rst, configs/collect_dataset.yaml, configs/collect_mirflickr_fza.yaml, lensless/recon/recon.py, rpi_requirements.txt, scripts/measure/collect_dataset_on_device.py
=> Measuring datasets with 3D printed masks

.github/workflows/python_no_pycsou.yml, .github/workflows/python_pycsou.yml, setup.py
=> Update test versions.

configs/collect_dataset.yaml, scripts/measure/collect_dataset_on_device.py
=> Fix increasing exposure, by removing fixed frame rate.

lensless/recon/utils.py
=> Fix for random shifts.

configs/upload_dataset_huggingface.yaml, configs/upload_tapecam_mirflickr_ambient.yaml, scripts/data/rename_mirflickr25k.py, scripts/data/upload_dataset_huggingface.py
=> Add support for uploading dataset with ambient lighting.

docs/source/examples.rst
Added a new notebook that showcases background subtraction and also the aligning of images
=> New example notebook for background subtraction

lensless/utils/dataset.py, setup.py
=> Fixes for when no background is present.

CONTRIBUTING.rst, README.rst, docs/source/examples.rst
=> Improvements in docs.
